# Generated by Django 4.1.7 on 2023-02-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('imagem_post', models.ImageField(upload_to='')),
                ('resumo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
            ],
        ),
    ]
